// 滑卡驗收（T-001）。先清 localStorage 的 seen/saved/hidden 再跑。全部布林 true 才算過。
(async () => {
  const R = {}; const wait = (ms) => new Promise((r) => setTimeout(r, ms));
  const seen = () => JSON.parse(localStorage.getItem('rent591.seen') || '[]');
  const saved = () => JSON.parse(localStorage.getItem('rent591.saved') || '[]');
  const hidden = () => JSON.parse(localStorage.getItem('rent591.hidden') || '[]');
  const frontId = () => +document.querySelector('.sc.front')?.dataset.id || null;
  const remain = () => +document.querySelector('.sw .t small')?.textContent.match(/\d+/)[0];
  document.querySelector('#resetAll').click();
  document.querySelector('#swOpen, #mSwipe').click(); await wait(300);
  R.opened = !!document.querySelector('.sw') && history.state?.swipe === 1;
  R.remain0 = remain();
  const a = frontId();
  document.querySelector('[data-sw=no]').click(); await wait(400);
  R.leftSeen = seen().includes(a); R.leftNotHidden = !hidden().includes(a); R.leftNotSaved = !saved().includes(a);
  R.frontChanged = frontId() !== a;
  const b = frontId();
  document.querySelector('[data-sw=yes]').click(); await wait(400);
  R.rightSaved = saved().includes(b); R.rightSeen = seen().includes(b);
  document.querySelector('[data-sw=undo]').click(); await wait(300);
  R.undoFront = frontId() === b; R.undoUnseen = !seen().includes(b); R.undoUnsaved = !saved().includes(b);
  document.querySelector('[data-sw=undo]').click(); await wait(300);
  R.undoTwiceFront = frontId() === a; R.undoBtnDisabled = document.querySelector('[data-sw=undo]').disabled;
  document.querySelector('.sc.front [data-det]').click(); await wait(300);
  R.detailOverSwipe = !!document.querySelector('.ov') && !!document.querySelector('.sw');
  R.detailFromSwipeNotSeen = !seen().includes(a);
  history.back(); await wait(350);
  R.backToSwipe = !document.querySelector('.ov') && !!document.querySelector('.sw');
  document.querySelector('[data-swfilt]').click(); await wait(200);
  [...document.querySelectorAll('#lineChips .chip')].find((c) => c.textContent.trim() === '板南線').click(); await wait(200);
  R.filterNarrowed = remain() < R.remain0;
  document.querySelector('#filtDone').click(); await wait(350);
  R.drawerClosed = !document.querySelector('aside.open');
  history.back(); await wait(350);
  R.closedByBack = !document.querySelector('.sw');
  document.querySelector('#resetAll').click();
  const cardOf = (id) => [...document.querySelectorAll('.card')].find((c) => c.querySelector('.ttl')?.href.endsWith('/' + id) || c.querySelector('.ttl')?.href.includes('/' + id + '/'));
  R.skippedVisibleInAll = !!cardOf(a) && cardOf(a).querySelector('.badge.seen')?.textContent === '已看';
  document.querySelector('[data-view=unseen]').click();
  R.skippedHiddenInUnseen = !cardOf(a);
  document.querySelector('[data-view=active]').click();
  R.allTrue = Object.values(R).filter((v) => typeof v === 'boolean').every(Boolean);
  return R;
})();
