name: bisect-v12-configure-pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
